# Generated by Django 3.2 on 2021-05-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_suyog1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suyog1',
        ),
    ]
