# Generated by Django 3.2 on 2021-05-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_suyog1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addiction', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_locality', models.CharField(max_length=100)),
                ('addr_district', models.CharField(max_length=50)),
                ('addr_state', models.CharField(max_length=50)),
                ('addr_country', models.CharField(max_length=50)),
                ('addr_pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Busy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDL', models.FloatField()),
                ('LDL', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('phone_no', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Glocose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_meal', models.FloatField()),
                ('post_meal', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('other_info', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PastDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastDiseases', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'LGBT'), ('N', 'Dont want to reveal')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('phone_no', models.CharField(max_length=120)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Suyog',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.person')),
                ('speciality', models.CharField(max_length=120)),
                ('appoinment_duration', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('lunch_start', models.DateField()),
                ('lunch_end', models.DateField()),
                ('break_start', models.DateField()),
                ('break_end', models.DateField()),
                ('charge_per_app', models.FloatField()),
            ],
            bases=('profiles.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.person')),
                ('married', models.BooleanField(default=False)),
                ('occupation', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('education', models.CharField(choices=[('PRE', '7th'), ('SSC', '10th'), ('HSC', '12th'), ('GRD', 'Graduate'), ('PG', 'Post Graduate'), ('DR', 'PHD'), ('N', 'Dont want to reveal')], max_length=3)),
                ('records', models.CharField(max_length=150)),
                ('sleep_start', models.DateField()),
                ('sleep_end', models.DateField()),
            ],
            bases=('profiles.person',),
        ),
        migrations.AddField(
            model_name='other',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
        migrations.AddField(
            model_name='weight',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doctor'),
        ),
        migrations.AddField(
            model_name='slot',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='rating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doctor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='pastdiseases',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='height',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='glocose',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='cholesterol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='busy',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doctor'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='allergies',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='addictions',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('doctor', 'patient')},
        ),
    ]
