# Generated by Django 3.2 on 2021-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210506_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sleep_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sleep_start',
            field=models.DateTimeField(),
        ),
    ]
