# Generated by Django 3.2 on 2021-05-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210506_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='break_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='break_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lunch_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lunch_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sleep_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sleep_start',
            field=models.TimeField(),
        ),
    ]
