# Generated by Django 3.2 on 2021-05-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_doctor_practice_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='media',
        ),
        migrations.AddField(
            model_name='person',
            name='media',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='addiction',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_locality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='allergies',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='busy',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='busy',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busy',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cholesterol',
            name='HDL',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cholesterol',
            name='LDL',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cholesterol',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appoinment_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='break_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='break_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='charge_per_app',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lunch_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lunch_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='glocose',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='glocose',
            name='post_meal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='glocose',
            name='pre_meal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='height',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='height',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='other_info',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='key',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='value',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pastdiseases',
            name='past_diseases',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'LGBT'), ('N', 'Dont want to reveal')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='profiles.person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='profiles.doctor'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
